import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import { FloatingNavDemo } from '@/components/header/header';
import MusicButton from '@/components/home/music-button';

const outfit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Wedding & Engagement - Ramdani Yuliyani',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <FloatingNavDemo />
      <body className={outfit.className}>
        <Toaster />
        <main>{children}</main>
        <MusicButton />
      </body>
    </html>
  );
}
