import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/navigation/navigation';

const outfit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Wedding & Engagement - Ajeng Aril',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <main>{children}</main>
        <Navigation />
      </body>
    </html>
  );
}
